### ISSUE TITLE
Just started a pr0gramm python api repo

### ISSUE THREAD

**Issue by davidmann4** [mopsalarm/pr0gramm-meta#1]
maybe we can move some of your code to the new repo - making the API accessable to more people

gerne auch in Deutsch

**Comment by mopsalarm** [comment]
Tuh dir keinen Zwang an. Nutze was du möchtest. Zu deinen ersten Zeilen Code:

Guck dir requests http://docs.python-requests.org/en/latest/ an und nenne dein Modul nicht "pr0gramm-api", das hier geht nämlich  nicht:`import pr0gramm-api`

```
In [1]: import a-b
  File "<ipython-input-1-60fdecd72915>", line 1
    import a-b
            ^
SyntaxError: invalid syntax
```

**Comment by mopsalarm** [comment]
Das hier kann insbesondere interessant für dich sein. Ein paar Techniken, die dir das Mappen der Daten vereinfacht. Stichwort namedtuple und **kwargs: https://github.com/mopsalarm/pr0gramm-meta/blob/master/update/main.py#L92

**Comment by davidmann4** [comment]
cool thx, schau ich mir an!

**Comment by davidmann4** [comment]
hast du echt gut gemacht! danke für den hinweis - vorallem das "page management" ist super easy.

Dein code rennt auf 2.6 bis 3.2 ?

**Comment by mopsalarm** [comment]
Die Methode dort wollte überall laufen. Der Rest des Programms läuft kontrolliert im docker Container uns ist nur auf 3.4 getestet. Das sollte auch dein Ziel für die Entwicklung sein. Du solltest aktuell keine große Energie mehr in Python 2.6 und 3.0 bis 3.2 stecken.
